server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_ae682407f6bd
    token: b8b6
    app-id: wx19161231a52a4ec8
    app-secret: e31237a5cb1a5e2c6f03f7aae5ddafc9
    template-id: R7pC3HpyZQpJ45C1gEI9ph_F4Mtepje5IZHykb8DH5k

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:13306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app-id: 9021000162692780
  merchant-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCn5BWJTv92JV8+t5Gt2Ju3rZiVNcRjMtPiBBifycre9Lleg6+PospGw1Hai7vnc0MQekXYioQDzarlfAK4MiVY9BjMNnV1wnyZvJ+8kGR9OaAjIrfWNCO9eSXZkFAHp4hDrYFHJKst7I0qred6q4DHhpbN+tcZFHcmX4WpABnrBZAJpjKSWSHTQDzJye2UIWpl6Jl4Dz1uzJXbC68XZGyYqR0CrQVqebsxwcI9DqrVd537JIUxK18r97m6OXeAxrn+7g+jt037TKi1vrZKLCXQgLjDRFTQ3nW5UVGoPvWD8lMBE8pEflg3r5urQmzg+c71rcdpZXhpLRoOg1/H5i+jAgMBAAECggEAOfm6MiM0djDrlfW/+Z9uDlyE7ymU+ohnwImXkz4Ury8k/+1LZ7dYUF1MW8KbDY6w3vTKP799XO7dj8dmDQNMAE6ybXp0z0hszI3lPzFBcji/AsMPZom0uc4m8t0xtaL1nCFDHjUcY4xnJxDMeYDVxJDGbLStKHz3tCmSN0zQpmZB5iqLQWmKK7IL2JUPoPzEMbTD2Pzy08fNHCpP/jf00wGwCVEwVvnK3luinKA2/j8Nis8QbC0tPhMvnQE9afBc9Rxz5fCPe3ngfIlXszx2L+Omr4bFZmmwzY85sj+noEJKS6DFLMghZxWMdHSy7e2U6qq3bpSZkZBnR0D9BJ6UsQKBgQDs1uhq3ghgILR4+G/0ad2q/dHI4UUw+TboeXQPIjPCiyjcxiK6j3QLgsopa33ZEjE7rUVbSe4dKzFXIMqKeuxdpMdT2t7oh5x29gflH7knw1LCQswTN7u8DTW7hZBrq3osxZHJn2/5UEPdmmTtTYohikJz7QYq+ssGsIiMjpJMyQKBgQC1eTWl0HkfTQfFdlNUsHQU2fpb67LlL/mv6lwiOEU0yzf6hWXQuvCrpLZ/SN/cLQSqBfdhP/DI1paEQu7HnMGoHS/OOtdz38rM5gHEY1uMn3eTCL0/mu7nJ5mCAZcofCGPyO29THUuwg7jXHjrc1mQexzu9BX/4tnWMjYBhy5LCwKBgH6TCFl82jsNn4X7OFIGdipZRlG2WvUma3ro1eb0n3b8SlVbKtpLqngwaPyj7vkg6OD85FE6fKBoIhFve+9wbHxLgR/GnFTnjO5i5KtGPf0LPWKGsmwe4B1LbgkPA7UXSs88s4JuzDgQ9oQrbH8KbqUoMAWmiiJUMEcd94wu8e9JAoGBAIaE5uOW+XHeY9hXscWhVyrtucvRl7aULX3dN5aWJ5bO3RvzLlnfeO+DFVSc7HQFWuO9sHaCMzZs+v3nr6B/7n1zxTAWJgda6LWh+cVd8Ur4Gmb/n2k6q8TlccEQ9L+p5Cb1RmV/+41BhE+9CFVgGBAlcnkergAUZG2GosnXLtWpAoGBANHsaKJW1bJ2bXY8I4NX23aynBv1tPE+HwSFoAqVIMlDYDXzK6MSFmse5CyyvKtF5YXACGsDwf2vzjPUFFmsS0FDk17P+dmxRG1S6kxL922A1rI8UQDJaZAYkonpUZg9rVetJdsHPjzU4iSquKgUrNaa3wdyFlsS7swrkjbJGlL7
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmu4Jqe2xPKCOWrNgjo/incK9M4rf7PJURzN3LMKnEenNVgKvVL9ptPhZvGkvJ3M0rAatKlfe9lqIWL9scoxe0Z1GoTFOTuAR2uQF8lTg1/2q7bvdP7uJsUpHXncEks0RCR6h/SRkL5uubg1iEXZRCPXyO/9XEXqKc6wmLYO4aHQMO27eGg2p8WrPvFyNbtXnUCVC8kiwIyRFr7VUNLv5v9woMRv2qqz74nM2koC+rSfpKfKObWiOP6DH5zG0evrL3tTXY0PlBMb2MZRQuu2Ks1ff371Nf7iLGA1Wsj4rs8NPOv/NIXWul4SYHpJ5dAInBNzQgql7blsG1w+L3rq75QIDAQAB
  notify-url: http://localhost:8080/api/pay/notify/alipay
  return-url: https://baidu.com
  gateway-url: https://openapi.alipaydev.com/gateway.do

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml